"""init

Revision ID: c7d7ef10b07d
Revises: 
Create Date: 2023-02-13 12:46:31.340553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c7d7ef10b07d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "launch",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("details", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mission",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("launch_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["launch_id"], ["launch.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rocket",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("launch_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["launch_id"], ["launch.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rocket")
    op.drop_table("mission")
    op.drop_table("launch")
    # ### end Alembic commands ###
